# Site settings
title: DeepInfer- Deep Learning Deployment Toolkit for Medical Imagino0p-9u7ytrew34563424g

email: deepinfer@gmail.com
description: DeepInfer is an open-source toolkit for medical image analysis and processing with deep learning models. DeepInfer seamlessly integrates deep learning technology into the existing medical image analysis platforms such as 3D Slicer. It allows clinical researchers and biomedical engineers to deploy multi-platform pre-trained deep learning models and use task-specific deep models, without the need for further software development and configuration.

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://deepinfer.github.io" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
# data-ad-slot: 2973388149
# data-ad-client: ca-pub-9204963049240271
# google_ad_client: ca-pub-9204963049240271

google_analytics: "UA-100441285-1"
# addthis_id: ra-5644da281510c62f
# disqus_account: jeky-new-age

social:
  - title: twitter
    url: https://twitter.com/deepinfer
  - title: github
    url: http://github.com/deepinfer

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
